// this file is automatically generated by git.version.js script
const buildInfo = {
  version: '',
  revision: '82e1956',
  branch: 'develop',
  commit_time: '2021-10-18 20:23:30 +0200',
  build_time: 'Wed Oct 27 2021 10:04:56 GMT+0200 (Central European Summer Time)',
};
export default buildInfo;
