swagger: "2.0"
info:
  version: 1.0.0
  title: datablue
  description: datablue
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoint
  - name: Basics
    description: Endpoints for getting fountain data
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json
  - text/html


definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /metadata/fountain_properties:
    get:
      description: "Fetch general metadata for fountain properties. For example: whether OpenStreetMap or Wikidata are preferred places to store the information."
      responses:
        200:
          description: Returns property metadata.

  /metadata/locations:
    get:
      description: "Fetch general metadata for locations, including bounds and official operator information."
      responses:
        200:
          description: Returns location metadata.

  /fountain:
    get:
      description: Fetch detailed fountain information based on coordinates or identifier
      parameters:
        - name: queryType
          in: query
          type: string
          enum: [byCoords, byId]
          default: byCoords
          description: how to query the fountains
          required: true
        - name: database
          in: query
          type: string
          enum: [datablue, operator, wikidata, osm]
          example: wikidata
          description: database for which the provided identifier is valid
        - name: city
          in: query
          type: string
          enum: [zurich, geneva, basel]
          example: zurich_old_town
          required: false
          description: name of city for which fountains are to be served
        - name: idval
          in: query
          type: string
          example: Q27229889
          description: identifier used for fountain
        - name: lat
          in: query
          schema:
            type: float
          example: 47.364622
          description: approximate latitude of requested fountain, only required if querying by coords
        - name: lng
          in: query
          schema:
            type: float
          example: 8.537836
          description: approximate longitude of requested fountain, only required if querying by coords
        - name: radius
          in: query
          schema:
            type: float
          default: 10.0
          description: radius in meters in which fountains should be searched
      responses:
        200:
          description: Returns a fountain with metadata collected from OSM
        204:
          description: No fountain found at location.
        500:
          description: Swagger error.
  /fountains:
    get:
      description: Fetch fountains within bounding box
      parameters:
        - name: city
          in: query
          type: string
          enum: [zurich, geneva, basel]
          example: zurich
          required: true
          description: name of city for which fountains are to be served
        - name: refresh
          in: query
          type: boolean
          default: false
          description: indicates whether to force a refresh of the dataset
        - name: essential
          in: query
          type: boolean
          default: true
          description: indicates whether to return only the essential data
      responses:
        200:
          description: Returns a collection of fountains with metadata collected from OSM and Wikidata.
        204:
          description: No fountains found at location.
        500:
          description: internal server error.

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification